
# Catppuccin Frappe
[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#303446"
foreground = "#c6d0f5"
dim_foreground = "#c6d0f5"
bright_foreground = "#c6d0f5"

[colors.cursor]
text = "#303446"
cursor = "#f2d5cf"

[colors.vi_mode_cursor]
text = "#303446"
cursor = "#babbf1"

[colors.search.matches]
foreground = "#303446"
background = "#a5adce"

[colors.search.focused_match]
foreground = "#303446"
background = "#a6d189"

[colors.footer_bar]
foreground = "#303446"
background = "#a5adce"

[colors.hints.start]
foreground = "#303446"
background = "#e5c890"

[colors.hints.end]
foreground = "#303446"
background = "#a5adce"

[colors.selection]
text = "#303446"
background = "#f2d5cf"

[colors.normal]
black = "#51576d"
red = "#e78284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#f4b8e4"
cyan = "#81c8be"
white = "#b5bfe2"

[colors.bright]
black = "#626880"
red = "#e78284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#f4b8e4"
cyan = "#81c8be"
white = "#a5adce"

[colors.dim]
black = "#51576d"
red = "#e78284"
green = "#a6d189"
yellow = "#e5c890"
blue = "#8caaee"
magenta = "#f4b8e4"
cyan = "#81c8be"
white = "#b5bfe2"

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "0.95"

[font.normal]
family = "FantasqueSansM Nerd Font Mono"
#family = "ComicShannsMono Nerd Font"

[font]
size = 13

[scrolling]
history = 10000
multiplier = 1

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
dynamic_padding = true
dynamic_title = false

[window.padding]
x = 2
y = 2

[general]
live_config_reload = true
working_directory = "None"

[terminal]
