---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require: []
domains: []
reporters:
- rubocop
- typecheck
require_paths: []
plugins:
- solargraph-rails
- solargraph-rails-patch-for-rails71
max_files: 5000
